/*
 * Set and Tune API
 *
 * API for managing sets and tunes
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimodel

type ImportInfo struct {

	Warnings []string `json:"warnings,omitempty"`

	Errors []string `json:"errors,omitempty"`

	Infos []string `json:"infos,omitempty"`
}
