/*
 * Set and Tune API
 *
 * API for managing sets and tunes
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimodel

import "github.com/google/uuid"

type Tune struct {

	// Unique identifier for an object
	Id uuid.UUID `json:"id" binding:"required"`

	Title string `json:"title" binding:"required"`

	Type string `json:"type,omitempty"`

	TimeSig string `json:"timeSig,omitempty"`

	Composer string `json:"composer,omitempty"`

	Arranger string `json:"arranger,omitempty"`
}
