/*
 * Set and Tune API
 *
 * API for managing sets and tunes
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimodel

type Health200ResponseDetails struct {

	Database Health200ResponseDetailsDatabase `json:"database,omitempty"`
}
