// Code generated by MockGen. DO NOT EDIT.
// Source: tune_fixer.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	music_model "banduslib/internal/common/music_model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTuneFixer is a mock of TuneFixer interface.
type MockTuneFixer struct {
	ctrl     *gomock.Controller
	recorder *MockTuneFixerMockRecorder
}

// MockTuneFixerMockRecorder is the mock recorder for MockTuneFixer.
type MockTuneFixerMockRecorder struct {
	mock *MockTuneFixer
}

// NewMockTuneFixer creates a new mock instance.
func NewMockTuneFixer(ctrl *gomock.Controller) *MockTuneFixer {
	mock := &MockTuneFixer{ctrl: ctrl}
	mock.recorder = &MockTuneFixerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTuneFixer) EXPECT() *MockTuneFixerMockRecorder {
	return m.recorder
}

// Fix mocks base method.
func (m *MockTuneFixer) Fix(muMo music_model.MusicModel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fix", muMo)
}

// Fix indicates an expected call of Fix.
func (mr *MockTuneFixerMockRecorder) Fix(muMo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fix", reflect.TypeOf((*MockTuneFixer)(nil).Fix), muMo)
}
