// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ApiRouter is an autogenerated mock type for the ApiRouter type
type ApiRouter struct {
	mock.Mock
}

type ApiRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *ApiRouter) EXPECT() *ApiRouter_Expecter {
	return &ApiRouter_Expecter{mock: &_m.Mock}
}

// GetEngine provides a mock function with given fields:
func (_m *ApiRouter) GetEngine() *gin.Engine {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEngine")
	}

	var r0 *gin.Engine
	if rf, ok := ret.Get(0).(func() *gin.Engine); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gin.Engine)
		}
	}

	return r0
}

// ApiRouter_GetEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEngine'
type ApiRouter_GetEngine_Call struct {
	*mock.Call
}

// GetEngine is a helper method to define mock.On call
func (_e *ApiRouter_Expecter) GetEngine() *ApiRouter_GetEngine_Call {
	return &ApiRouter_GetEngine_Call{Call: _e.mock.On("GetEngine")}
}

func (_c *ApiRouter_GetEngine_Call) Run(run func()) *ApiRouter_GetEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiRouter_GetEngine_Call) Return(_a0 *gin.Engine) *ApiRouter_GetEngine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ApiRouter_GetEngine_Call) RunAndReturn(run func() *gin.Engine) *ApiRouter_GetEngine_Call {
	_c.Call.Return(run)
	return _c
}

// NewApiRouter creates a new instance of ApiRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApiRouter {
	mock := &ApiRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
