/*
 * Set and Tune API
 *
 * API for managing sets and tunes
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimodel
import "github.com/google/uuid"

type ObjectId struct {

	// Unique identifier for an object
	Id uuid.UUID `json:"id"`
}
