/*
 * Set and Tune API
 *
 * API for managing sets and tunes
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimodel
import "github.com/google/uuid"

type ImportTune struct {

	// Unique identifier for an object
	Id uuid.UUID `json:"id"`

	Title string `json:"title"`

	Type string `json:"type,omitempty"`

	TimeSig string `json:"timeSig,omitempty"`

	Composer string `json:"composer,omitempty"`

	Arranger string `json:"arranger,omitempty"`

	Set *BasicMusicSet `json:"set,omitempty"`

	// true, if tune was imported into database, false if a tune with this title was already there
	ImportedToDatabase bool `json:"importedToDatabase,omitempty"`

	Warnings []string `json:"warnings,omitempty"`

	Errors []string `json:"errors,omitempty"`

	Infos []string `json:"infos,omitempty"`
}
