/*
 * Set and Tune API
 *
 * API for managing sets and tunes
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimodel
import "github.com/google/uuid"

// MusicSet - Called MusicSet and not only Set because of name clash in e.g. typescript
type MusicSet struct {

	// Unique identifier for an object
	Id uuid.UUID `json:"id"`

	// The name of the Set
	Title string `json:"title"`

	// A description of the Set
	Description string `json:"description,omitempty"`

	// The name of the creator of the set
	Creator string `json:"creator,omitempty"`

	Tunes []Tune `json:"tunes,omitempty"`
}
