// Code generated by "enumer -json -yaml -type=EmbellishmentType"; DO NOT EDIT.

package symbols

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EmbellishmentTypeName = "NoEmbellishmentSingleGraceDoublingHalfDoublingThumbDoublingStrikeGStrikeThumbStrikeHalfStrikeGripHalfGripThumbGripGGripTaorluathBubblyBirlThrowDHeavyThrowDPeleThumbPeleHalfPeleDoubleStrikeGDoubleStrikeThumbDoubleStrikeHalfDoubleStrikeTripleStrikeGTripleStrikeThumbTripleStrikeHalfTripleStrikeDDoubleGraceEDoubleGraceFDoubleGraceGDoubleGraceThumbDoubleGrace"

var _EmbellishmentTypeIndex = [...]uint16{0, 15, 26, 34, 46, 59, 65, 72, 83, 93, 97, 105, 114, 119, 128, 134, 138, 144, 155, 159, 168, 176, 188, 201, 218, 234, 246, 259, 276, 292, 304, 316, 328, 340, 356}

const _EmbellishmentTypeLowerName = "noembellishmentsinglegracedoublinghalfdoublingthumbdoublingstrikegstrikethumbstrikehalfstrikegriphalfgripthumbgripggriptaorluathbubblybirlthrowdheavythrowdpelethumbpelehalfpeledoublestrikegdoublestrikethumbdoublestrikehalfdoublestriketriplestrikegtriplestrikethumbtriplestrikehalftriplestrikeddoublegraceedoublegracefdoublegracegdoublegracethumbdoublegrace"

func (i EmbellishmentType) String() string {
	if i >= EmbellishmentType(len(_EmbellishmentTypeIndex)-1) {
		return fmt.Sprintf("EmbellishmentType(%d)", i)
	}
	return _EmbellishmentTypeName[_EmbellishmentTypeIndex[i]:_EmbellishmentTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EmbellishmentTypeNoOp() {
	var x [1]struct{}
	_ = x[NoEmbellishment-(0)]
	_ = x[SingleGrace-(1)]
	_ = x[Doubling-(2)]
	_ = x[HalfDoubling-(3)]
	_ = x[ThumbDoubling-(4)]
	_ = x[Strike-(5)]
	_ = x[GStrike-(6)]
	_ = x[ThumbStrike-(7)]
	_ = x[HalfStrike-(8)]
	_ = x[Grip-(9)]
	_ = x[HalfGrip-(10)]
	_ = x[ThumbGrip-(11)]
	_ = x[GGrip-(12)]
	_ = x[Taorluath-(13)]
	_ = x[Bubbly-(14)]
	_ = x[Birl-(15)]
	_ = x[ThrowD-(16)]
	_ = x[HeavyThrowD-(17)]
	_ = x[Pele-(18)]
	_ = x[ThumbPele-(19)]
	_ = x[HalfPele-(20)]
	_ = x[DoubleStrike-(21)]
	_ = x[GDoubleStrike-(22)]
	_ = x[ThumbDoubleStrike-(23)]
	_ = x[HalfDoubleStrike-(24)]
	_ = x[TripleStrike-(25)]
	_ = x[GTripleStrike-(26)]
	_ = x[ThumbTripleStrike-(27)]
	_ = x[HalfTripleStrike-(28)]
	_ = x[DDoubleGrace-(29)]
	_ = x[EDoubleGrace-(30)]
	_ = x[FDoubleGrace-(31)]
	_ = x[GDoubleGrace-(32)]
	_ = x[ThumbDoubleGrace-(33)]
}

var _EmbellishmentTypeValues = []EmbellishmentType{NoEmbellishment, SingleGrace, Doubling, HalfDoubling, ThumbDoubling, Strike, GStrike, ThumbStrike, HalfStrike, Grip, HalfGrip, ThumbGrip, GGrip, Taorluath, Bubbly, Birl, ThrowD, HeavyThrowD, Pele, ThumbPele, HalfPele, DoubleStrike, GDoubleStrike, ThumbDoubleStrike, HalfDoubleStrike, TripleStrike, GTripleStrike, ThumbTripleStrike, HalfTripleStrike, DDoubleGrace, EDoubleGrace, FDoubleGrace, GDoubleGrace, ThumbDoubleGrace}

var _EmbellishmentTypeNameToValueMap = map[string]EmbellishmentType{
	_EmbellishmentTypeName[0:15]:         NoEmbellishment,
	_EmbellishmentTypeLowerName[0:15]:    NoEmbellishment,
	_EmbellishmentTypeName[15:26]:        SingleGrace,
	_EmbellishmentTypeLowerName[15:26]:   SingleGrace,
	_EmbellishmentTypeName[26:34]:        Doubling,
	_EmbellishmentTypeLowerName[26:34]:   Doubling,
	_EmbellishmentTypeName[34:46]:        HalfDoubling,
	_EmbellishmentTypeLowerName[34:46]:   HalfDoubling,
	_EmbellishmentTypeName[46:59]:        ThumbDoubling,
	_EmbellishmentTypeLowerName[46:59]:   ThumbDoubling,
	_EmbellishmentTypeName[59:65]:        Strike,
	_EmbellishmentTypeLowerName[59:65]:   Strike,
	_EmbellishmentTypeName[65:72]:        GStrike,
	_EmbellishmentTypeLowerName[65:72]:   GStrike,
	_EmbellishmentTypeName[72:83]:        ThumbStrike,
	_EmbellishmentTypeLowerName[72:83]:   ThumbStrike,
	_EmbellishmentTypeName[83:93]:        HalfStrike,
	_EmbellishmentTypeLowerName[83:93]:   HalfStrike,
	_EmbellishmentTypeName[93:97]:        Grip,
	_EmbellishmentTypeLowerName[93:97]:   Grip,
	_EmbellishmentTypeName[97:105]:       HalfGrip,
	_EmbellishmentTypeLowerName[97:105]:  HalfGrip,
	_EmbellishmentTypeName[105:114]:      ThumbGrip,
	_EmbellishmentTypeLowerName[105:114]: ThumbGrip,
	_EmbellishmentTypeName[114:119]:      GGrip,
	_EmbellishmentTypeLowerName[114:119]: GGrip,
	_EmbellishmentTypeName[119:128]:      Taorluath,
	_EmbellishmentTypeLowerName[119:128]: Taorluath,
	_EmbellishmentTypeName[128:134]:      Bubbly,
	_EmbellishmentTypeLowerName[128:134]: Bubbly,
	_EmbellishmentTypeName[134:138]:      Birl,
	_EmbellishmentTypeLowerName[134:138]: Birl,
	_EmbellishmentTypeName[138:144]:      ThrowD,
	_EmbellishmentTypeLowerName[138:144]: ThrowD,
	_EmbellishmentTypeName[144:155]:      HeavyThrowD,
	_EmbellishmentTypeLowerName[144:155]: HeavyThrowD,
	_EmbellishmentTypeName[155:159]:      Pele,
	_EmbellishmentTypeLowerName[155:159]: Pele,
	_EmbellishmentTypeName[159:168]:      ThumbPele,
	_EmbellishmentTypeLowerName[159:168]: ThumbPele,
	_EmbellishmentTypeName[168:176]:      HalfPele,
	_EmbellishmentTypeLowerName[168:176]: HalfPele,
	_EmbellishmentTypeName[176:188]:      DoubleStrike,
	_EmbellishmentTypeLowerName[176:188]: DoubleStrike,
	_EmbellishmentTypeName[188:201]:      GDoubleStrike,
	_EmbellishmentTypeLowerName[188:201]: GDoubleStrike,
	_EmbellishmentTypeName[201:218]:      ThumbDoubleStrike,
	_EmbellishmentTypeLowerName[201:218]: ThumbDoubleStrike,
	_EmbellishmentTypeName[218:234]:      HalfDoubleStrike,
	_EmbellishmentTypeLowerName[218:234]: HalfDoubleStrike,
	_EmbellishmentTypeName[234:246]:      TripleStrike,
	_EmbellishmentTypeLowerName[234:246]: TripleStrike,
	_EmbellishmentTypeName[246:259]:      GTripleStrike,
	_EmbellishmentTypeLowerName[246:259]: GTripleStrike,
	_EmbellishmentTypeName[259:276]:      ThumbTripleStrike,
	_EmbellishmentTypeLowerName[259:276]: ThumbTripleStrike,
	_EmbellishmentTypeName[276:292]:      HalfTripleStrike,
	_EmbellishmentTypeLowerName[276:292]: HalfTripleStrike,
	_EmbellishmentTypeName[292:304]:      DDoubleGrace,
	_EmbellishmentTypeLowerName[292:304]: DDoubleGrace,
	_EmbellishmentTypeName[304:316]:      EDoubleGrace,
	_EmbellishmentTypeLowerName[304:316]: EDoubleGrace,
	_EmbellishmentTypeName[316:328]:      FDoubleGrace,
	_EmbellishmentTypeLowerName[316:328]: FDoubleGrace,
	_EmbellishmentTypeName[328:340]:      GDoubleGrace,
	_EmbellishmentTypeLowerName[328:340]: GDoubleGrace,
	_EmbellishmentTypeName[340:356]:      ThumbDoubleGrace,
	_EmbellishmentTypeLowerName[340:356]: ThumbDoubleGrace,
}

var _EmbellishmentTypeNames = []string{
	_EmbellishmentTypeName[0:15],
	_EmbellishmentTypeName[15:26],
	_EmbellishmentTypeName[26:34],
	_EmbellishmentTypeName[34:46],
	_EmbellishmentTypeName[46:59],
	_EmbellishmentTypeName[59:65],
	_EmbellishmentTypeName[65:72],
	_EmbellishmentTypeName[72:83],
	_EmbellishmentTypeName[83:93],
	_EmbellishmentTypeName[93:97],
	_EmbellishmentTypeName[97:105],
	_EmbellishmentTypeName[105:114],
	_EmbellishmentTypeName[114:119],
	_EmbellishmentTypeName[119:128],
	_EmbellishmentTypeName[128:134],
	_EmbellishmentTypeName[134:138],
	_EmbellishmentTypeName[138:144],
	_EmbellishmentTypeName[144:155],
	_EmbellishmentTypeName[155:159],
	_EmbellishmentTypeName[159:168],
	_EmbellishmentTypeName[168:176],
	_EmbellishmentTypeName[176:188],
	_EmbellishmentTypeName[188:201],
	_EmbellishmentTypeName[201:218],
	_EmbellishmentTypeName[218:234],
	_EmbellishmentTypeName[234:246],
	_EmbellishmentTypeName[246:259],
	_EmbellishmentTypeName[259:276],
	_EmbellishmentTypeName[276:292],
	_EmbellishmentTypeName[292:304],
	_EmbellishmentTypeName[304:316],
	_EmbellishmentTypeName[316:328],
	_EmbellishmentTypeName[328:340],
	_EmbellishmentTypeName[340:356],
}

// EmbellishmentTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EmbellishmentTypeString(s string) (EmbellishmentType, error) {
	if val, ok := _EmbellishmentTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EmbellishmentTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EmbellishmentType values", s)
}

// EmbellishmentTypeValues returns all values of the enum
func EmbellishmentTypeValues() []EmbellishmentType {
	return _EmbellishmentTypeValues
}

// EmbellishmentTypeStrings returns a slice of all String values of the enum
func EmbellishmentTypeStrings() []string {
	strs := make([]string, len(_EmbellishmentTypeNames))
	copy(strs, _EmbellishmentTypeNames)
	return strs
}

// IsAEmbellishmentType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EmbellishmentType) IsAEmbellishmentType() bool {
	for _, v := range _EmbellishmentTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EmbellishmentType
func (i EmbellishmentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EmbellishmentType
func (i *EmbellishmentType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EmbellishmentType should be a string, got %s", data)
	}

	var err error
	*i, err = EmbellishmentTypeString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for EmbellishmentType
func (i EmbellishmentType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for EmbellishmentType
func (i *EmbellishmentType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = EmbellishmentTypeString(s)
	return err
}
